export const surpriseMePrompts = [
    'una butaca en forma de aguacate',
    'una pintura al óleo surrealista y onírica de Salvador Dalí de un gato jugando al ajedrez',
    'osos de peluche comprando comestibles en Japón, ukiyo-e',
    'una pintura al óleo de Matisse de un robot humanoide jugando al ajedrez',
    'un científico loco panda mezclando químicos brillantes, arte digital',
    'una fotografía macro de 35 mm de dos ratones en Hawái, cada uno lleva puesto un diminuto traje de baño y carga diminutas tablas de surf, arte digital',
    'renderizado 3D de un lindo pez tropical en un acuario sobre un fondo azul oscuro, arte digital',
    'un astronauta descansando en un resort tropical en el espacio, vaporwave',
    'un retrato en pintura al óleo de un capibara vistiendo ropa real medieval y una corona ornamental sobre un fondo oscuro',
    'una vidriera que representa una hamburguesa y papas fritas',
    'un dibujo a lápiz y acuarela de una ciudad brillante en el futuro con coches voladores',
    'una zona de estar interior iluminada por la luz solar con una piscina de agua clara y otra de agua rosa translúcido pastel, junto a una ventana grande, arte digital',
    'un shiba inu adivino leyendo tu destino en una hamburguesa gigante, arte digital',
    '"una nutria de mar con un arete de perla" por Johannes Vermeer',
    'un dibujo con pastel al óleo de un gato molesto en una nave espacial',
    'una pintura de un zorro en el estilo de La noche estrellada',
    'un tazón de sopa que parece un monstruo, tejido con lana',
    'un robot de juguete de peluche sentado contra una pared amarilla',
    'un atardecer en estilo synthwave sobre el agua reflejante del mar, arte digital',
    'dos torres futuristas con un puente cubierto de vegetación exuberante, arte digital',
    'un renderizado 3D de un globo aerostático arcoíris volando sobre un lago reflejante',
    'la portada de un cómic de un superhéroe vistiendo audífonos',
    'una explosión centrada de polvo colorido sobre un fondo negro',
    'una foto de un perro Samoyedo con la lengua afuera abrazando a un gato siamés blanco',
    'una foto de un monstruo de piel blanca parado en una habitación morada',
    'una foto de la escultura de David de Miguel Ángel vistiendo audífonos y tocando música como DJ',
    'un samurai montando un caballo en Marte, lomografía',
    'un moderno y elegante Cadillac conduciendo por la autopista Gardiner con el centro de Toronto de fondo, con un destello de lente, fotografía de 50mm',
    'una fotografía realista de una mujer joven con ojos azules y cabello rubio',
    'un hombre parado frente a una puerta estelar hacia otra dimensión',
];
